version: "3.9"

services:
  #  PostgreSQL
  database-postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_DB=search_entertainment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5444:5432"